"use client";

import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";

type TransitionKey =
  | "top-down"
  | "bottom-up"
  | "left-right"
  | "right-left"
  | "zoom-in"
  | "zoom-out"
  | "fade";

type TransitionConfig = {
  id: string;
  fromPage: number;
  toPage: number;
  transition: TransitionKey;
  duration: number;
};

const TRANSITION_OPTIONS: Array<{ value: TransitionKey; label: string; description: string }> = [
  { value: "top-down", label: "Top -> Down", description: "A próxima tela entra de cima para baixo." },
  { value: "bottom-up", label: "Bottom -> Up", description: "A próxima tela entra de baixo para cima." },
  { value: "left-right", label: "Left -> Right", description: "A próxima tela entra da esquerda para a direita." },
  { value: "right-left", label: "Right -> Left", description: "A próxima tela entra da direita para a esquerda." },
  { value: "zoom-in", label: "Zoom In", description: "A próxima tela cresce suavemente até ocupar o frame." },
  { value: "zoom-out", label: "Zoom Out", description: "A tela atual afasta e revela a próxima." },
  { value: "fade", label: "Fade", description: "Transição limpa por opacidade entre as telas." },
];

const SCREEN_COLORS = ["#0f172a", "#111827", "#1e1b4b", "#052e16"] as const;

function getPrompt(config: TransitionConfig): string {
  const option = TRANSITION_OPTIONS.find((item) => item.value === config.transition);
  return `Create a page transition from Screen ${config.fromPage} to Screen ${config.toPage}. Use "${option?.label}" movement, duration ${config.duration.toFixed(1)}s, easing "easeInOut", and preserve readability during motion.`;
}

function getAnimationClasses(transition: TransitionKey, active: boolean): string {
  if (!active) return "opacity-0";
  switch (transition) {
    case "top-down":
      return "animate-[slideDown_700ms_ease-in-out_forwards]";
    case "bottom-up":
      return "animate-[slideUp_700ms_ease-in-out_forwards]";
    case "left-right":
      return "animate-[slideRight_700ms_ease-in-out_forwards]";
    case "right-left":
      return "animate-[slideLeft_700ms_ease-in-out_forwards]";
    case "zoom-in":
      return "animate-[zoomIn_700ms_ease-in-out_forwards]";
    case "zoom-out":
      return "animate-[zoomOut_700ms_ease-in-out_forwards]";
    default:
      return "animate-[fadeIn_700ms_ease-in-out_forwards]";
  }
}

export function PageTransitionLab() {
  const [configs, setConfigs] = useState<TransitionConfig[]>([
    { id: "t-1", fromPage: 1, toPage: 2, transition: "right-left", duration: 0.8 },
    { id: "t-2", fromPage: 2, toPage: 3, transition: "top-down", duration: 0.9 },
    { id: "t-3", fromPage: 3, toPage: 4, transition: "left-right", duration: 0.8 },
  ]);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [previewStep, setPreviewStep] = useState(0);
  const [codeOpen, setCodeOpen] = useState(false);

  const generatedCode = useMemo(() => {
    const entries = configs
      .map(
        (config) =>
          `  "${config.fromPage}-${config.toPage}": { transition: "${config.transition}", duration: ${config.duration.toFixed(1)} },`,
      )
      .join("\n");
    return `// Page transition map generated by DevServer\nexport const pageTransitions = {\n${entries}\n};\n\n// Example usage with framer-motion\n/*\n<motion.div\n  key={pathname}\n  initial={{ opacity: 0, x: 40 }}\n  animate={{ opacity: 1, x: 0 }}\n  exit={{ opacity: 0, x: -40 }}\n  transition={{ duration: 0.8, ease: "easeInOut" }}\n>\n  {children}\n</motion.div>\n*/`;
  }, [configs]);

  const handleUpdate = <K extends keyof TransitionConfig>(id: string, key: K, value: TransitionConfig[K]) => {
    setConfigs((prev) => prev.map((cfg) => (cfg.id === id ? { ...cfg, [key]: value } : cfg)));
  };

  const runPreview = () => {
    setPreviewStep(0);
    setPreviewOpen(true);
    let index = 0;
    const loop = setInterval(() => {
      index += 1;
      setPreviewStep(index);
      if (index > configs.length) clearInterval(loop);
    }, 1100);
  };

  return (
    <section className="mx-auto w-full max-w-7xl px-4 pb-16 pt-28">
      <style>{`
        @keyframes slideDown { from { transform: translateY(-90%); opacity: 0; } to { transform: translateY(0); opacity: 1; } }
        @keyframes slideUp { from { transform: translateY(90%); opacity: 0; } to { transform: translateY(0); opacity: 1; } }
        @keyframes slideLeft { from { transform: translateX(90%); opacity: 0; } to { transform: translateX(0); opacity: 1; } }
        @keyframes slideRight { from { transform: translateX(-90%); opacity: 0; } to { transform: translateX(0); opacity: 1; } }
        @keyframes zoomIn { from { transform: scale(0.75); opacity: 0; } to { transform: scale(1); opacity: 1; } }
        @keyframes zoomOut { from { transform: scale(1.2); opacity: 0; } to { transform: scale(1); opacity: 1; } }
        @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
      `}</style>

      <div className="rounded-3xl border border-border bg-card/70 p-6 shadow-xl backdrop-blur md:p-8">
        <h1 className="text-2xl font-semibold md:text-4xl">Organizador de animacoes entre paginas</h1>
        <p className="mt-2 max-w-3xl text-sm text-muted-foreground md:text-base">
          Configure as transicoes entre 4 telas do seu site. Cada linha representa uma passagem entre paginas, com opcoes visuais e prompt tecnico ao lado.
        </p>

        <div className="mt-8 grid gap-4">
          {configs.map((config) => {
            const option = TRANSITION_OPTIONS.find((item) => item.value === config.transition);
            return (
              <article key={config.id} className="grid gap-4 rounded-2xl border border-border/70 bg-background/70 p-4 md:grid-cols-[1.15fr_1fr]">
                <div className="space-y-3">
                  <p className="text-sm font-semibold">
                    Pagina {config.fromPage} {"->"} Pagina {config.toPage}
                  </p>
                  <label className="block space-y-1">
                    <span className="text-xs uppercase tracking-wide text-muted-foreground">Tipo de animacao</span>
                    <select
                      value={config.transition}
                      onChange={(event) => handleUpdate(config.id, "transition", event.target.value as TransitionKey)}
                      className="h-10 w-full rounded-lg border border-border bg-card px-3 text-sm outline-none ring-primary/20 focus:ring-2"
                    >
                      {TRANSITION_OPTIONS.map((item) => (
                        <option key={item.value} value={item.value}>
                          {item.label}
                        </option>
                      ))}
                    </select>
                  </label>
                  <label className="block space-y-1">
                    <span className="text-xs uppercase tracking-wide text-muted-foreground">Duracao ({config.duration.toFixed(1)}s)</span>
                    <input
                      type="range"
                      min={0.3}
                      max={2}
                      step={0.1}
                      value={config.duration}
                      onChange={(event) => handleUpdate(config.id, "duration", Number(event.target.value))}
                      className="w-full accent-primary"
                    />
                  </label>
                  <p className="text-xs text-muted-foreground">{option?.description}</p>
                </div>

                <div className="rounded-xl border border-dashed border-primary/30 bg-primary/5 p-3">
                  <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-primary">Prompt</p>
                  <p className="text-xs leading-relaxed text-muted-foreground">{getPrompt(config)}</p>
                </div>
              </article>
            );
          })}
        </div>

        <div className="mt-6 flex flex-wrap gap-3">
          <Button type="button" onClick={runPreview} className="rounded-full">
            Ver como ficou
          </Button>
          <Button type="button" variant="outline" className="rounded-full" onClick={() => setCodeOpen((prev) => !prev)}>
            {codeOpen ? "Ocultar codigo" : "Ver codigo"}
          </Button>
        </div>

        {codeOpen ? (
          <pre className="mt-4 max-h-80 overflow-auto rounded-2xl border border-border bg-black/90 p-4 text-xs leading-relaxed text-emerald-200">
            <code>{generatedCode}</code>
          </pre>
        ) : null}
      </div>

      {previewOpen ? (
        <div className="fixed inset-0 z-[120] flex items-center justify-center bg-black/70 p-4">
          <div className="w-full max-w-4xl rounded-2xl border border-border bg-card p-4 shadow-2xl md:p-6">
            <div className="mb-4 flex items-center justify-between">
              <h2 className="text-lg font-semibold">Preview das 4 paginas</h2>
              <Button type="button" size="sm" variant="outline" className="rounded-full" onClick={() => setPreviewOpen(false)}>
                Fechar
              </Button>
            </div>
            <div className="relative h-[360px] overflow-hidden rounded-xl border border-border bg-muted/30">
              {[1, 2, 3, 4].map((page, index) => {
                const active = previewStep >= index;
                const transition = configs[Math.max(0, index - 1)]?.transition ?? "fade";
                return (
                  <div
                    key={page}
                    className={`absolute inset-0 flex items-center justify-center ${getAnimationClasses(transition, active)}`}
                    style={{ background: SCREEN_COLORS[index] }}
                  >
                    <div className="rounded-2xl border border-white/20 bg-black/25 px-8 py-6 text-center text-white backdrop-blur">
                      <p className="text-xs uppercase tracking-[0.2em] text-white/70">Tela</p>
                      <p className="mt-2 text-4xl font-bold">{page}</p>
                    </div>
                  </div>
                );
              })}
            </div>
            <p className="mt-3 text-xs text-muted-foreground">As telas aparecem uma por uma com as transicoes configuradas acima.</p>
          </div>
        </div>
      ) : null}
    </section>
  );
}

