"use client";

import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";

type TransitionKey =
  | "top-down"
  | "bottom-up"
  | "left-right"
  | "right-left"
  | "zoom-in"
  | "zoom-out"
  | "fade";

type TransitionConfig = {
  id: string;
  fromPage: number;
  toPage: number;
  transition: TransitionKey;
  duration: number;
};

const TRANSITION_OPTIONS: Array<{ value: TransitionKey; label: string; description: string }> = [
  { value: "top-down", label: "De cima para baixo", description: "A próxima tela entra de cima para baixo." },
  { value: "bottom-up", label: "De baixo para cima", description: "A próxima tela entra de baixo para cima." },
  { value: "left-right", label: "Da esquerda para direita", description: "A próxima tela entra da esquerda para a direita." },
  { value: "right-left", label: "Da direita para esquerda", description: "A próxima tela entra da direita para a esquerda." },
  { value: "zoom-in", label: "Zoom aproximando", description: "A próxima tela cresce suavemente até ocupar o frame." },
  { value: "zoom-out", label: "Zoom afastando", description: "A tela atual afasta e revela a próxima." },
  { value: "fade", label: "Fade suave", description: "Transição limpa por opacidade entre as telas." },
];

const SCREEN_COLORS = ["#0f172a", "#111827", "#1e1b4b", "#052e16", "#3f1d2e", "#1f2937"] as const;

function getPrompt(config: TransitionConfig): string {
  const option = TRANSITION_OPTIONS.find((item) => item.value === config.transition);
  return `Create a page transition from Screen ${config.fromPage} to Screen ${config.toPage}. Use "${option?.label}" movement, duration ${config.duration.toFixed(1)}s, easing "easeInOut", and preserve readability during motion.`;
}

function getAnimationClass(transition: TransitionKey): string {
  switch (transition) {
    case "top-down":
      return "animate-[slideDown_var(--d)_ease-in-out_forwards]";
    case "bottom-up":
      return "animate-[slideUp_var(--d)_ease-in-out_forwards]";
    case "left-right":
      return "animate-[slideRight_var(--d)_ease-in-out_forwards]";
    case "right-left":
      return "animate-[slideLeft_var(--d)_ease-in-out_forwards]";
    case "zoom-in":
      return "animate-[zoomIn_var(--d)_ease-in-out_forwards]";
    case "zoom-out":
      return "animate-[zoomOut_var(--d)_ease-in-out_forwards]";
    default:
      return "animate-[fadeIn_var(--d)_ease-in-out_forwards]";
  }
}

export function PageTransitionLab() {
  const [configs, setConfigs] = useState<TransitionConfig[]>([
    { id: "t-1", fromPage: 1, toPage: 2, transition: "right-left", duration: 0.8 },
    { id: "t-2", fromPage: 2, toPage: 3, transition: "top-down", duration: 0.9 },
    { id: "t-3", fromPage: 3, toPage: 4, transition: "left-right", duration: 0.8 },
  ]);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [scrollPreviewProgress, setScrollPreviewProgress] = useState(0);
  const [codeOpen, setCodeOpen] = useState(false);
  const [rowPreviewTick, setRowPreviewTick] = useState<Record<string, number>>({});

  const pageCount = configs.length + 1;

  const generatedCode = useMemo(() => {
    const entries = configs
      .map(
        (config) =>
          `  "${config.fromPage}-${config.toPage}": { transition: "${config.transition}", duration: ${config.duration.toFixed(1)} },`,
      )
      .join("\n");
    return `// Page transition map generated by DevServer\nexport const pageTransitions = {\n${entries}\n};\n\n// Example usage with framer-motion\n/*\n<motion.div\n  key={pathname}\n  initial={{ opacity: 0, x: 40 }}\n  animate={{ opacity: 1, x: 0 }}\n  exit={{ opacity: 0, x: -40 }}\n  transition={{ duration: 0.8, ease: "easeInOut" }}\n>\n  {children}\n</motion.div>\n*/`;
  }, [configs]);

  const handleUpdate = <K extends keyof TransitionConfig>(id: string, key: K, value: TransitionConfig[K]) => {
    setConfigs((prev) => prev.map((cfg) => (cfg.id === id ? { ...cfg, [key]: value } : cfg)));
  };

  const createPage = () => {
    setConfigs((prev) => {
      const nextFrom = prev.length + 1;
      const nextTo = nextFrom + 1;
      return [...prev, { id: `t-${crypto.randomUUID()}`, fromPage: nextFrom, toPage: nextTo, transition: "fade", duration: 0.8 }];
    });
  };

  const removePage = () => {
    setConfigs((prev) => {
      if (prev.length <= 1) return prev;
      return prev.slice(0, -1).map((cfg, idx) => ({ ...cfg, fromPage: idx + 1, toPage: idx + 2 }));
    });
  };

  const playRowPreview = (id: string) => {
    setRowPreviewTick((prev) => ({ ...prev, [id]: (prev[id] ?? 0) + 1 }));
  };

  const runPreview = () => {
    setScrollPreviewProgress(0);
    setPreviewOpen(true);
  };

  const handleScrollPreview = (event: React.UIEvent<HTMLDivElement>) => {
    const el = event.currentTarget;
    const max = Math.max(1, el.scrollHeight - el.clientHeight);
    setScrollPreviewProgress(el.scrollTop / max);
  };

  const segmentProgress = scrollPreviewProgress * Math.max(1, pageCount - 1);
  const currentSegment = Math.min(pageCount - 1, Math.floor(segmentProgress));
  const localProgress = Math.min(1, Math.max(0, segmentProgress - currentSegment));
  const currentTransition = configs[currentSegment]?.transition ?? "fade";

  const getIncomingStyle = (transition: TransitionKey, progress: number) => {
    const p = Math.min(1, Math.max(0, progress));
    switch (transition) {
      case "top-down":
        return { transform: `translateY(${(-100 + p * 100).toFixed(2)}%)`, opacity: p };
      case "bottom-up":
        return { transform: `translateY(${(100 - p * 100).toFixed(2)}%)`, opacity: p };
      case "left-right":
        return { transform: `translateX(${(-100 + p * 100).toFixed(2)}%)`, opacity: p };
      case "right-left":
        return { transform: `translateX(${(100 - p * 100).toFixed(2)}%)`, opacity: p };
      case "zoom-in":
        return { transform: `scale(${(0.75 + p * 0.25).toFixed(3)})`, opacity: p };
      case "zoom-out":
        return { transform: `scale(${(1.2 - p * 0.2).toFixed(3)})`, opacity: p };
      default:
        return { transform: "translateX(0%)", opacity: p };
    }
  };

  return (
    <section className="mx-auto w-full max-w-7xl px-4 pb-16 pt-28">
      <style>{`
        @keyframes slideDown { from { transform: translateY(-90%); opacity: 0; } to { transform: translateY(0); opacity: 1; } }
        @keyframes slideUp { from { transform: translateY(90%); opacity: 0; } to { transform: translateY(0); opacity: 1; } }
        @keyframes slideLeft { from { transform: translateX(90%); opacity: 0; } to { transform: translateX(0); opacity: 1; } }
        @keyframes slideRight { from { transform: translateX(-90%); opacity: 0; } to { transform: translateX(0); opacity: 1; } }
        @keyframes zoomIn { from { transform: scale(0.75); opacity: 0; } to { transform: scale(1); opacity: 1; } }
        @keyframes zoomOut { from { transform: scale(1.2); opacity: 0; } to { transform: scale(1); opacity: 1; } }
        @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
      `}</style>

      <div className="rounded-3xl border border-border bg-card/70 p-6 shadow-xl backdrop-blur md:p-8">
        <h1 className="text-2xl font-semibold md:text-4xl">Organizador de animacoes entre paginas</h1>
        <p className="mt-2 max-w-3xl text-sm text-muted-foreground md:text-base">
          Configure as transicoes entre telas do seu site. Cada linha representa uma passagem entre paginas, com tipo da animacao, prompt tecnico e preview visual ao lado.
        </p>

        <div className="mt-5 flex flex-wrap gap-3">
          <Button type="button" variant="outline" className="rounded-full" onClick={createPage}>
            Criar pagina
          </Button>
          <Button type="button" variant="outline" className="rounded-full" onClick={removePage} disabled={pageCount <= 2}>
            Excluir ultima pagina
          </Button>
          <p className="self-center text-xs text-muted-foreground">Paginas atuais: {pageCount}</p>
        </div>

        <div className="mt-8 grid gap-4">
          {configs.map((config) => {
            const option = TRANSITION_OPTIONS.find((item) => item.value === config.transition);
            const fromColor = SCREEN_COLORS[(config.fromPage - 1) % SCREEN_COLORS.length]!;
            const toColor = SCREEN_COLORS[(config.toPage - 1) % SCREEN_COLORS.length]!;
            return (
              <article key={config.id} className="grid gap-4 rounded-2xl border border-border/70 bg-background/70 p-4 md:grid-cols-[1.1fr_1fr]">
                <div className="space-y-3">
                  <p className="text-sm font-semibold">
                    Pagina {config.fromPage} {"->"} Pagina {config.toPage}
                  </p>
                  <label className="block space-y-1">
                    <span className="text-xs uppercase tracking-wide text-muted-foreground">Tipo de animacao</span>
                    <select
                      value={config.transition}
                      onChange={(event) => handleUpdate(config.id, "transition", event.target.value as TransitionKey)}
                      className="h-10 w-full rounded-lg border border-border bg-card px-3 text-sm outline-none ring-primary/20 focus:ring-2"
                    >
                      {TRANSITION_OPTIONS.map((item) => (
                        <option key={item.value} value={item.value}>
                          {item.label}
                        </option>
                      ))}
                    </select>
                  </label>
                  <label className="block space-y-1">
                    <span className="text-xs uppercase tracking-wide text-muted-foreground">Duracao ({config.duration.toFixed(1)}s)</span>
                    <input
                      type="range"
                      min={0.3}
                      max={2}
                      step={0.1}
                      value={config.duration}
                      onChange={(event) => handleUpdate(config.id, "duration", Number(event.target.value))}
                      className="w-full accent-primary"
                    />
                  </label>
                  <p className="text-xs text-muted-foreground">{option?.description}</p>
                </div>

                <div className="space-y-3 rounded-xl border border-dashed border-primary/30 bg-primary/5 p-3">
                  <div>
                    <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-primary">Prompt</p>
                    <p className="text-xs leading-relaxed text-muted-foreground">{getPrompt(config)}</p>
                  </div>

                  <div>
                    <div className="mb-2 flex items-center justify-between">
                      <p className="text-xs font-semibold uppercase tracking-wide text-primary">Visualizacao</p>
                      <Button type="button" size="sm" variant="secondary" className="h-7 rounded-full px-3 text-[11px]" onClick={() => playRowPreview(config.id)}>
                        Ver animacao
                      </Button>
                    </div>
                    <div className="relative h-28 overflow-hidden rounded-lg border border-border/80 bg-black/50">
                      <div className="absolute inset-0 flex items-center justify-center text-xs text-white/90" style={{ background: fromColor }}>
                        Tela {config.fromPage}
                      </div>
                      <div
                        key={`${config.id}-${rowPreviewTick[config.id] ?? 0}`}
                        className={`absolute inset-0 flex items-center justify-center text-xs text-white ${getAnimationClass(config.transition)}`}
                        style={{ background: toColor, ["--d" as string]: `${config.duration}s` }}
                      >
                        Tela {config.toPage}
                      </div>
                    </div>
                  </div>
                </div>
              </article>
            );
          })}
        </div>

        <div className="mt-6 flex flex-wrap gap-3">
          <Button type="button" onClick={runPreview} className="rounded-full">
            Ver como ficou
          </Button>
          <Button type="button" variant="outline" className="rounded-full" onClick={() => setCodeOpen((prev) => !prev)}>
            {codeOpen ? "Ocultar codigo" : "Ver codigo"}
          </Button>
        </div>

        {codeOpen ? (
          <pre className="mt-4 max-h-80 overflow-auto rounded-2xl border border-border bg-black/90 p-4 text-xs leading-relaxed text-emerald-200">
            <code>{generatedCode}</code>
          </pre>
        ) : null}
      </div>

      {previewOpen ? (
        <div className="fixed inset-0 z-[120] flex items-center justify-center bg-black/70 p-4">
          <div className="w-full max-w-4xl rounded-2xl border border-border bg-card p-4 shadow-2xl md:p-6">
            <div className="mb-4 flex items-center justify-between">
              <h2 className="text-lg font-semibold">Preview por scroll das paginas</h2>
              <Button type="button" size="sm" variant="outline" className="rounded-full" onClick={() => setPreviewOpen(false)}>
                Fechar
              </Button>
            </div>
            <div className="grid gap-3 md:grid-cols-[1fr_210px]">
              <div className="relative h-[360px] overflow-hidden rounded-xl border border-border bg-muted/30">
                <div
                  className="absolute inset-0 flex items-center justify-center"
                  style={{ background: SCREEN_COLORS[currentSegment % SCREEN_COLORS.length] }}
                >
                  <div className="rounded-2xl border border-white/20 bg-black/25 px-8 py-6 text-center text-white backdrop-blur">
                    <p className="text-xs uppercase tracking-[0.2em] text-white/70">Tela atual</p>
                    <p className="mt-2 text-4xl font-bold">{currentSegment + 1}</p>
                  </div>
                </div>
                <div
                  className="absolute inset-0 flex items-center justify-center"
                  style={{
                    background: SCREEN_COLORS[(currentSegment + 1) % SCREEN_COLORS.length],
                    ...getIncomingStyle(currentTransition, localProgress),
                  }}
                >
                  <div className="rounded-2xl border border-white/20 bg-black/25 px-8 py-6 text-center text-white backdrop-blur">
                    <p className="text-xs uppercase tracking-[0.2em] text-white/70">Proxima tela</p>
                    <p className="mt-2 text-4xl font-bold">{Math.min(pageCount, currentSegment + 2)}</p>
                  </div>
                </div>
              </div>
              <div
                className="h-[360px] overflow-y-auto rounded-xl border border-border bg-background/60 p-3"
                onScroll={handleScrollPreview}
              >
                <div className="h-[1100px]">
                  <p className="text-xs text-muted-foreground">Role aqui para acionar as transicoes.</p>
                </div>
              </div>
            </div>
            <p className="mt-3 text-xs text-muted-foreground">Agora o preview e 100% por scroll: role para avancar entre as telas e ver a animacao.</p>
          </div>
        </div>
      ) : null}
    </section>
  );
}

